# Generated by Django 5.2 on 2025-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
