# Generated by Django 5.2 on 2025-04-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crude', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crude',
            new_name='Crudapp',
        ),
    ]
